server:
  servlet:
    context-path: /content-calendar-api

spring:
  application:
    name: content-calendar-api
  #  # H2 Database Configuration
  #  h2:
  #    console:
  #      enabled: true
  #  datasource:
  #    generate-unique-name: false
  #    name: content
  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: warn
