server:
  servlet:
    context-path: /content-calendar-api
  port: 8080

info:
  app:
    name: Content Calendar API
    description: API para gestionar un calendario de contenidos digitales
    version: 1.0.0
  build:
    artifact: content-calendar-api
    name: Content Calendar API
    time: ${timestamp}
    version: 1.0.0

spring:
  application:
    name: content-calendar-api
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: contentcalendarapi
  # Determina si Spring Boot debe ejecutar scripts SQL de inicializacion al iniciar la aplicacion.
  # En este caso, inicializa el schema.sql de 'resources'
  sql:
    init:
      mode: always

management:
  endpoint:
    health:
      show-details: always

cc:
  home:
    welcome-msg: "Hola! Bienvenido a la API del Calendario de Contenidos."

---
spring:
  config:
    activate:
      on-profile: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"

cc:
  home:
    welcome-msg: "Hola! Bienvenido a la API del Calendario de Contenidos. [Entorno de Desarrollo]"
