DROP TABLE IF EXISTS Content;

CREATE TABLE IF NOT EXISTS Content
(
    id           SERIAL PRIMARY KEY,
    title        VARCHAR(255) NOT NULL,
    description  TEXT,
    status       VARCHAR(20)  NOT NULL,
    content_type VARCHAR(50)  NOT NULL,
    date_created TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated TIMESTAMP,
    url          VARCHAR(255)
);

INSERT INTO Content (title, description, status, content_type, date_created, date_updated, url)
VALUES ('Exploring AI Trends', 'An in-depth look into the latest trends in artificial intelligence.', 'IDEA', 'ARTICLE',
        '2024-01-15 09:00:00', NULL, 'https://www.techinsights.com/exploring-ai-trends'),
       ('Understanding Quantum Computing', 'A beginner’s guide to quantum computing concepts and applications.',
        'IN_PROGRESS', 'ARTICLE', '2024-02-01 14:00:00', NULL,
        'https://www.sciencehub.com/understanding-quantum-computing'),
       ('AI in Healthcare: Future Prospects', 'How AI is transforming healthcare and what to expect in the future.',
        'PUBLISHED', 'ARTICLE', '2024-02-20 16:30:00', '2024-02-21 10:00:00',
        'https://www.healthtech.com/ai-in-healthcare'),
       ('Building Scalable Web Apps',
        'A comprehensive course on building scalable web applications using modern frameworks.', 'COMPLETED', 'COURSE',
        '2024-03-01 11:00:00', '2024-03-15 09:00:00', 'https://www.developertools.com/building-scalable-web-apps'),
       ('Deep Learning for Beginners', 'Introduction to deep learning techniques and their applications.', 'IDEA',
        'COURSE', '2024-03-10 12:00:00', NULL, 'https://www.learningplatform.com/deep-learning-for-beginners'),
       ('Innovations in Renewable Energy', 'A conference talk discussing the latest innovations in renewable energy.',
        'PUBLISHED', 'CONFERENCE_TALK', '2024-03-20 10:00:00', '2024-03-21 11:00:00',
        'https://www.energyconferences.com/innovations-renewable-energy'),
       ('Effective SEO Strategies', 'Video tutorial on effective strategies for improving SEO.', 'IN_PROGRESS', 'VIDEO',
        '2024-04-05 13:00:00', NULL, 'https://www.videomarketing.com/effective-seo-strategies'),
       ('Mastering JavaScript', 'Advanced course on JavaScript programming and best practices.', 'IDEA', 'COURSE',
        '2024-04-10 15:00:00', NULL, 'https://www.codingacademy.com/mastering-javascript'),
       ('Social Media Marketing Essentials', 'Key techniques and tools for successful social media marketing.',
        'PUBLISHED', 'ARTICLE', '2024-04-15 09:30:00', '2024-04-16 10:00:00',
        'https://www.marketinginsights.com/social-media-marketing-essentials'),
       ('Future of Blockchain Technology', 'An exploration of how blockchain technology is expected to evolve.',
        'IN_PROGRESS', 'ARTICLE', '2024-05-01 08:00:00', NULL, 'https://www.blockchainfuture.com/future-of-blockchain'),
       ('Introduction to Data Science', 'A beginner-friendly course on data science concepts and tools.', 'COMPLETED',
        'COURSE', '2024-05-15 14:00:00', '2024-05-20 16:00:00',
        'https://www.datasciencecourse.com/introduction-to-data-science'),
       ('Developing Mobile Apps', 'Video series on the best practices for mobile app development.', 'PUBLISHED',
        'VIDEO', '2024-06-01 12:00:00', '2024-06-02 11:00:00', 'https://www.mobiledevs.com/developing-mobile-apps'),
       ('Cybersecurity Fundamentals', 'A comprehensive guide to the basics of cybersecurity.', 'IDEA', 'ARTICLE',
        '2024-06-10 10:00:00', NULL, 'https://www.cybersecuritybasics.com/fundamentals'),
       ('Creating Interactive Websites', 'Course on creating engaging and interactive websites using modern tools.',
        'IN_PROGRESS', 'COURSE', '2024-06-15 13:00:00', NULL, 'https://www.webdevacademy.com/interactive-websites'),
       ('AI and Ethics: A Discussion', 'A conference talk about the ethical considerations of artificial intelligence.',
        'PUBLISHED', 'CONFERENCE_TALK', '2024-07-01 11:00:00', '2024-07-02 12:00:00',
        'https://www.ethicsinai.com/ai-and-ethics'),
       ('The Rise of Virtual Reality', 'Exploring the rise and impact of virtual reality technologies.', 'COMPLETED',
        'ARTICLE', '2024-07-10 09:00:00', '2024-07-11 10:00:00', 'https://www.virtualrealitynews.com/rise-of-vr'),
       ('Machine Learning for Everyone', 'A course aimed at making machine learning accessible to everyone.',
        'IN_PROGRESS', 'COURSE', '2024-07-15 14:00:00', NULL, 'https://www.mlforall.com/machine-learning-course'),
       ('Advanced SQL Techniques', 'Video tutorial covering advanced SQL techniques for database management.', 'IDEA',
        'VIDEO', '2024-08-01 16:00:00', NULL, 'https://www.sqlskills.com/advanced-sql-techniques'),
       ('Digital Marketing Strategies', 'An article discussing effective digital marketing strategies for businesses.',
        'PUBLISHED', 'ARTICLE', '2024-08-10 09:30:00', '2024-08-11 11:00:00',
        'https://www.digitalmarketing.com/strategies'),
       ('Getting Started with Cloud Computing', 'Introduction to cloud computing and its benefits.', 'COMPLETED',
        'COURSE', '2024-08-20 11:00:00', '2024-08-21 12:00:00',
        'https://www.cloudacademy.com/getting-started-cloud-computing'),
       ('Robotics and Automation', 'Video course on robotics and automation technologies.', 'PUBLISHED', 'VIDEO',
        '2024-09-01 10:00:00', '2024-09-02 11:30:00', 'https://www.roboticscentral.com/robotics-automation'),
       ('Introduction to DevOps', 'An overview of DevOps principles and practices for modern development.',
        'IN_PROGRESS', 'COURSE', '2024-09-10 12:00:00', NULL, 'https://www.devopsacademy.com/introduction-to-devops'),
       ('Introduction to Python Programming', 'A beginner’s course on Python programming basics and applications.',
        'COMPLETED', 'COURSE', '2024-09-15 08:00:00', '2024-09-16 09:00:00',
        'https://www.pythoncourse.com/introduction-to-python'),
       ('Trends in Web Development', 'Exploring the latest trends and technologies in web development.', 'IDEA',
        'ARTICLE', '2024-10-01 10:00:00', NULL, 'https://www.webtrends.com/trends-in-web-development'),
       ('Mastering Git and GitHub', 'Video tutorial on advanced Git and GitHub techniques for version control.',
        'PUBLISHED', 'VIDEO', '2024-10-10 14:00:00', '2024-10-11 15:00:00', 'https://www.gitmastery.com/mastering-git'),
       ('The Future of Artificial Intelligence', 'An in-depth analysis of the potential future developments in AI.',
        'IN_PROGRESS', 'ARTICLE', '2024-10-15 16:00:00', NULL,
        'https://www.futureofai.com/the-future-of-artificial-intelligence'),
       ('Creating Effective Email Campaigns',
        'A course on designing and executing successful email marketing campaigns.', 'COMPLETED', 'COURSE',
        '2024-11-01 13:00:00', '2024-11-02 14:00:00', 'https://www.emailmarketing.com/effective-campaigns'),
       ('Introduction to Augmented Reality', 'Exploring the basics of augmented reality technology and applications.',
        'IDEA', 'ARTICLE', '2024-11-10 11:00:00', NULL, 'https://www.augmentedreality.com/introduction-to-ar'),
       ('Cybersecurity Best Practices',
        'Video guide on essential cybersecurity practices for individuals and organizations.', 'PUBLISHED', 'VIDEO',
        '2024-11-15 09:00:00', '2024-11-16 10:00:00', 'https://www.cybersecurityguide.com/best-practices'),
       ('The Role of Big Data in Modern Business',
        'An exploration of how big data is shaping business strategies today.', 'IN_PROGRESS', 'ARTICLE',
        '2024-12-01 15:00:00', NULL, 'https://www.bigdatabusiness.com/role-of-big-data'),
       ('Understanding DevOps Tools', 'Course on the various tools used in DevOps practices and how to leverage them.',
        'COMPLETED', 'COURSE', '2024-12-10 08:00:00', '2024-12-11 09:00:00',
        'https://www.devopstools.com/understanding-devops-tools'),
       ('Advancements in Machine Learning', 'Discussing recent advancements and research in machine learning.', 'IDEA',
        'ARTICLE', '2024-12-15 10:00:00', NULL, 'https://www.mlresearch.com/advancements-in-machine-learning'),
       ('Building Secure Web Applications',
        'Video series on best practices for securing web applications against threats.', 'PUBLISHED', 'VIDEO',
        '2025-01-01 11:00:00', '2025-01-02 12:00:00', 'https://www.securewebapps.com/building-secure-apps'),
       ('Introduction to Blockchain for Developers',
        'Course designed to introduce developers to blockchain technology and programming.', 'IN_PROGRESS', 'COURSE',
        '2025-01-10 13:00:00', NULL, 'https://www.blockchaindevs.com/introduction-to-blockchain'),
       ('AI for Data Analysis',
        'An article on how artificial intelligence is used for data analysis and interpretation.', 'PUBLISHED',
        'ARTICLE', '2025-01-15 09:30:00', '2025-01-16 10:00:00', 'https://www.aidataanalysis.com/ai-for-data-analysis'),
       ('Effective Remote Work Strategies',
        'A comprehensive guide on strategies for effective remote work and team management.', 'COMPLETED', 'ARTICLE',
        '2025-02-01 11:00:00', '2025-02-02 12:00:00', 'https://www.remoteworkstrategies.com/effective-remote-work'),
       ('Introduction to Cloud Security', 'Course on the fundamentals of cloud security and best practices.', 'IDEA',
        'COURSE', '2025-02-10 14:00:00', NULL, 'https://www.cloudsecuritycourse.com/introduction-to-cloud-security'),
       ('The Impact of 5G Technology', 'A look at how 5G technology is changing various industries and services.',
        'IN_PROGRESS', 'ARTICLE', '2025-02-15 16:00:00', NULL, 'https://www.5gimpact.com/impact-of-5g-technology'),
       ('Developing Augmented Reality Apps',
        'Video tutorial on creating applications using augmented reality technology.', 'PUBLISHED', 'VIDEO',
        '2025-03-01 10:00:00', '2025-03-02 11:00:00', 'https://www.arappdev.com/developing-ar-apps'),
       ('Advanced Database Management', 'Course covering advanced techniques in managing and optimizing databases.',
        'COMPLETED', 'COURSE', '2025-03-10 13:00:00', '2025-03-11 14:00:00',
        'https://www.dbmanagement.com/advanced-techniques'),
       ('Blockchain in Financial Services', 'Exploring the application of blockchain technology in financial services.',
        'IDEA', 'ARTICLE', '2025-03-15 09:00:00', NULL,
        'https://www.blockchainfinance.com/blockchain-in-financial-services'),
       ('Using AI for Personalization', 'Video on how AI can be used to personalize user experiences and services.',
        'IN_PROGRESS', 'VIDEO', '2025-04-01 11:00:00', NULL,
        'https://www.aipersonalization.com/using-ai-for-personalization'),
       ('Creating Interactive Data Visualizations',
        'Course on creating engaging and interactive data visualizations for better insights.', 'PUBLISHED', 'COURSE',
        '2025-04-10 12:00:00', '2025-04-11 13:00:00', 'https://www.datavisualization.com/interactive-visualizations'),
       ('Ethical Considerations in AI',
        'An article discussing the ethical implications and considerations in artificial intelligence.', 'IDEA',
        'ARTICLE', '2025-04-15 08:00:00', NULL, 'https://www.ethicalai.com/considerations-in-ai');


